# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
baseurl                 = "https://cybermagnolia.com/"
DefaultContentLanguage  = "en"
title                   = "CyberMagnolia"
theme                   = "hugo-future-imperfect-slim"
paginate                = 3
googleAnalytics         = "UA-182890047-1"
pluralizeListTitles     = false
disableLanguages        = ['pl', 'fr', 'de', 'pt', 'es', 'zh-cn', 'zh-tw', 'ja', 'nl']

copyright               = "© 2020 Daria Grudzien"
enableEmoji             = true
enableRobotsTXT         = true

[markup.goldmark.renderer]
  unsafe                = true

[outputs]
  home                  = ["html", "json", "rss"]

[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = ""
  highlightjsLang       = []
  viewMorePostsLink     = "/blog/"
  readingTime           = true
  imageStretch          = ""
  removeBlur            = false
  socialShare           = ["twitter", "facebook", "linkedin", "email"]
  hideEmptyStats        = true

  [params.meta]
    description         = "CyberMagnolia—Women's Tech Collective."
    author              = "CyberMagnolia"
    favicon             = true
    svg                 = false
    faviconVersion      = "6"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "CyberMagnolia"
    dynamicTitles       = true
    searchMenu          = false
    shareMenu           = true
    languageMenu        = false

  [params.intro]
    # paragraph             = "Another fine, responsive site template by <a href='http://html5up.net'>HTML5 UP</a>."
    # temporarily disabled
    rssIntro              = false
    socialIntro           = false
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "/img/logo_dark.webp"
      shape               = "square"
      width               = "200"
      alt                 = "CyberMagnolia Logo"

  [params.sidebar]
    about               = "CyberMagnolia is a Women's Tech Collective of women working in technology joining together to share knowledge and experience, support each other and grow professionally in a friendly environment."
    postAmount          = 5
    categories          = false
    categoriesByCount   = false

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.staticman]
    enabled             = false
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "Speakers"
    identifier        = "speakers"
    url               = "/speakers/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "/blog/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 2

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Contact"
    identifier        = "contact"
    url               = "/contact/"
    pre               = "<i class='far fa-envelope'></i>"
    weight            = 6

[Languages]

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1

[social]
  twitter               = "cybermagnolia"
  instagram             = "cybermagnolia"
  github                = "cybermagnolia/cybermagnolia.com"
  # youtube               = ""
  linkedin_company      = "cybermagnolia"
  # facebook              = "example"
  # medium                = ""
  # email                 = "example"
  slack                 = "cybermagnolia"
